### PR TITLE
Fixed for Survivors of the Void

### PR DESCRIPTION
**Pull request by ZANdewanai**
Fixed and added capitalizations so visual studio likes the code more

### CODE REVIEW

**Comment by GrahamMThomas** [comment]
I'll take a look tomorrow.

**Comment by Zanzancomms** [comment]
ty

**Comment by Zanzancomms** [comment]
also, maybe delete the unused libraries, just kept them there to be sure

**Comment by GrahamMThomas** [comment]
So, first, I really hate the idea of checking in the game libraries into this repo. I'd rather let developers map to their own game libraries if they don't map to the normal location. Other big mods don't do this either because it's bad practice.

Second, Changing the variable casing is fine, I didn't install analyzers on this repo for some reason and apparently I was feeling pretty pythonic lmao. But also, I would move that into a separate PR so that it doesn't distract from your fix.

Third, I can't actually find the "Fix" that you are claiming to have made because of points 1 or 2.

Action Items for you:
1. Create a PR just with the fix (which I can't find)
2. Create a PR with your Code Styling changes (In general styling/linting changes should never be mixed with a feature PR for this exact reason)
3. Create another PR for the libraries reference change, not whatever you did (adding dlls to repo is generally a no-no), but look at the examples from some other modders. Here's an example I found from RiskOfOptions mod [RiskOfOptions.csproj](https://github.com/Rune580/RiskOfOptions/blob/eb6912b0d3ac90ca349f43a587944e7fb3c003e8/RiskOfOptions.csproj#L13) which I quite like.

Any of these PRs independently I'd be happy to test and merge.

**Comment by Zanzancomms** [comment]
ah okay sorry for the bother, ill close it then

**Pull request closed without merging**
